#!/bin/bash
#SBATCH --job-name="P3HT_Methylthiophene_2_Optimize_Monomer"
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH -t 1:0:00
#SBATCH -A ddp381
#SBATCH --mail-type=ALL
cd /expanse/lustre/scratch/theleonzhang/temp_project/Optimized_Monomers

module add cpu/0.15.4
module add gcc/9.2.0
module add openmpi/3.1.6
module add orca/4.2.1
orca P3HT_Methylthiophene_2_Optimize_Monomer.inp >> P3HT_Methylthiophene_2_Optimize_Monomer.out