#!/bin/bash
#PBS -N PEDOT_Methylthiophene_1_Optimize_Monomer
#PBS -o PEDOT_Methylthiophene_1_Optimize_Monomer
#PBS -q condo
#PBS -l nodes=1:ppn=1
#PBS -l walltime=2:00:00

cd /oasis/tscc/scratch/andrewk/Optimized_Monomers

export PATH=/home/andrewk/openmpi-3.1.4:/home/andrewk/orca_4_2_0_linux_x86-64_openmpi314/bin:$PATH
export RSH_COMMAND="/usr/bin/ssh -x"
export LD_LIBRARY_PATH=/home/andrewk/openmpi-3.1.4/lib
/home/andrewk/orca_4_2_0_linux_x86-64_openmpi314/orca PEDOT_Methylthiophene_1_Optimize_Monomer.inp >> PEDOT_Methylthiophene_1_Optimize_Monomer.out
