#!/bin/bash
#SBATCH --job-name="Methylthiophene_Dual_Hydrogenated"
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=64
#SBATCH -t 3:0:00
#SBATCH -A ddp381
#SBATCH --mail-type=ALL
cd /expanse/lustre/scratch/theleonzhang/temp_project/Interring_Bonds
module add cpu/0.15.4  
module add gcc/10.2.0  
module add mvapich2/2.3.6 
module add qchem/5.4
qchem Methylthiophene_Dihydrogenated_Syn.qcin >> Methylthiophene_Dihydrogenated_Syn.out
qchem Methylthiophene_Dihydrogenated_Anti.qcin >> Methylthiophene_Dihydrogenated_Anti.out