#!/bin/bash
#SBATCH --job-name="{Sim_Name}"
#SBATCH --output="lammpsgpu.%j.%N.out"
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --no-requeue
#SBATCH --gres=gpu:k80:4
#SBATCH -t 048:00:00
#SBATCH -A csd467
cd {path}

module unload mvapich2_ib
module unload intel
module load intel/2015.2.164
module load mvapich2_ib
module load cuda/8.0

mpirun -np 24 /oasis/scratch/comet/andrewk/temp_project/Mod_Lammps/lammps-11Aug17/src/lmp_gpu -sf gpu -pk gpu 4 -in in.{Sim_Name} -log log.{Sim_Name}
